# Generated by Django 4.2.1 on 2023-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=10, max_digits=100)),
                ('change_24h', models.DecimalField(decimal_places=10, max_digits=100)),
                ('trade_volume', models.DecimalField(decimal_places=10, max_digits=100)),
                ('vwap_24h', models.DecimalField(decimal_places=10, max_digits=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
