# Generated by Django 4.2.1 on 2023-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0003_alter_cryptocurrency_vwap_24h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='change_24h',
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='current_price',
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='trade_volume',
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='vwap_24h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True),
        ),
    ]
