# Generated by Django 4.2.1 on 2023-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0004_alter_cryptocurrency_change_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
