# Generated by Django 4.2.1 on 2023-05-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0006_cryptocurrency_if_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='if_favorite',
            new_name='is_favorite',
        ),
    ]
