# Generated by Django 4.2.1 on 2023-05-31 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptodata', '0007_rename_if_favorite_cryptocurrency_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='change_24h',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='trade_volume',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=25, null=True),
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodata.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
