# Generated by Django 4.2.1 on 2023-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0008_alter_cryptocurrency_change_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
