# Generated by Django 4.2.1 on 2023-05-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0009_alter_cryptocurrency_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='is_favorite',
        ),
    ]
